
name: blue-circle

recipe: laravel

excludes:
  - node_modules

config:
  database: mysql
  php: 7.4
  via: nginx
  webroot: public

proxy:
  mailhog:
    - mail.blue-circle.lndo.site
  pma:
    - pma.blue-circle.lndo.site

services:
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  pma:
    type: phpmyadmin
    ssl: true
    hosts:
      - database
